# Generated by Django 3.1.5 on 2021-01-21 10:29

from django.db import migrations, models
import django.db.models.deletion
import student_fee.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('student_management_app', '0006_auto_20210121_1559'),
    ]

    operations = [
        migrations.CreateModel(
            name='fees_collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inv_number', models.CharField(default=student_fee.models.generateInvNumber, max_length=25)),
                ('total_amt', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_type', models.CharField(max_length=10)),
                ('payment_mode', models.CharField(max_length=10)),
                ('tax_percent', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tax_amt', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('net_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('paid_amt', models.DecimalField(decimal_places=2, max_digits=10)),
                ('balance_amt', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_status', models.CharField(default='Pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(default='Anonymous', max_length=25)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(default='Anonymous', max_length=25)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_management_app.students')),
            ],
        ),
        migrations.CreateModel(
            name='fees_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fee_type', models.CharField(max_length=100)),
                ('fee_description', models.TextField(blank=True, null=True)),
                ('fee_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='fees_collection_items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(default='Anonymous', max_length=25)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(default='Anonymous', max_length=25)),
                ('fee_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_fee.fees_data')),
                ('fees_collection_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_fee.fees_collection')),
            ],
        ),
    ]
