# Generated by Django 3.1.5 on 2021-01-21 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0006_auto_20210121_1559'),
        ('student_management_app', '0006_auto_20210121_1552'),
    ]

    operations = [
    ]
