# Generated by Django 3.1.5 on 2021-01-22 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0008_auto_20210121_1647'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subjects',
            name='staff_id',
        ),
    ]
