# Generated by Django 3.1.5 on 2021-01-27 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0010_auto_20210123_1106'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='full_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[(1, 'HOD'), (2, 'Staff'), (3, 'parent')], default=1, max_length=10),
        ),
    ]
